[algokit]
min_version = "v2.6.0"

[project]
type = 'backend'
name = 'client'

[project.run]
# Commands intended for use locally and in CI
build = { commands = [
  'npm run build',
], description = 'Build the client' }

