#!/usr/bin/env bun

import { $ } from "bun";
import { join } from "path";
import { writeFileSync, chmodSync } from "fs";

async function buildStandalone() {
  console.log("🔨 Building standalone Linux executable...");

  try {
    // Clean previous builds
    console.log("🧹 Cleaning previous builds...");
    await $`rm -rf dist/standalone`;
    await $`mkdir -p dist/standalone`;

    // Build the TypeScript project
    console.log("📦 Building TypeScript project...");
    await $`bun run build`;

    // Create the standalone executable using Bun's bundler
    console.log("🚀 Creating standalone executable...");
    await $`bun build ./src/index.ts --target=bun --outdir=dist/standalone --compile --name=escreg`;

    // Create a shebang script wrapper for better compatibility
    console.log("📝 Creating executable wrapper...");
    const wrapperContent = `#!/usr/bin/env bun
// This file is auto-generated by the build process
// Standalone executable for escreg CLI

import { main } from "./index.js";

// Run the main function
main().catch((error) => {
  console.error("Error:", error);
  process.exit(1);
});
`;

    writeFileSync("dist/standalone/escreg-wrapper.js", wrapperContent);
    chmodSync("dist/standalone/escreg-wrapper.js", 0o755);

    // Create a simple shell script for maximum compatibility
    const shellScript = `#!/bin/bash
# Standalone escreg CLI executable
# This script runs the bundled JavaScript with Bun

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec bun "$SCRIPT_DIR/index.js" "$@"
`;

    writeFileSync("dist/standalone/escreg", shellScript);
    chmodSync("dist/standalone/escreg", 0o755);

    console.log("✅ Standalone executable created successfully!");
    console.log("📁 Output location: dist/standalone/");
    console.log("🚀 Executable: dist/standalone/escreg");
    console.log("📦 Bundled JS: dist/standalone/index.js");

    // Test the executable
    console.log("🧪 Testing executable...");
    const testResult = await $`./dist/standalone/escreg --version`;
    console.log("✅ Executable test passed!");

  } catch (error) {
    console.error("❌ Build failed:", error);
    process.exit(1);
  }
}

// Run the build
buildStandalone();
