#!/usr/bin/env bun

import { $ } from "bun";
import { writeFileSync, chmodSync, readFileSync } from "fs";
import { join } from "path";

async function buildExecutable() {
  console.log("🔨 Building standalone Linux executable with Bun...");

  try {
    // Clean previous builds
    console.log("🧹 Cleaning previous builds...");
    await $`rm -rf dist/executable`;
    await $`mkdir -p dist/executable`;

    // First, build the TypeScript project
    console.log("📦 Building TypeScript project...");
    await $`bun run build`;

    // Create a bundled version of the application
    console.log("📦 Bundling application...");
    await $`bun build ./src/index.ts --target=bun --outdir=dist/executable --name=escreg-bundle`;

    // Create the standalone executable using Bun's compile feature
    console.log("🚀 Compiling standalone executable...");
    
    // Create a main entry point for the executable
    const mainEntry = `#!/usr/bin/env bun
// Standalone escreg CLI executable
// Auto-generated by build process

// Import the bundled application
import "./escreg-bundle.js";

// Handle process termination gracefully
process.on('SIGINT', () => {
  console.log('\\nReceived SIGINT, shutting down gracefully...');
  process.exit(0);
});

process.on('SIGTERM', () => {
  console.log('\\nReceived SIGTERM, shutting down gracefully...');
  process.exit(0);
});
`;

    writeFileSync("dist/executable/main.js", mainEntry);

    // Compile to standalone executable
    console.log("🔧 Compiling to native executable...");
    await $`bun build dist/executable/main.js --target=bun --compile --name=escreg`;
    
    // Move the compiled executable to the correct location
    await $`mv escreg dist/executable/`;

    // Create a simple shell script as fallback
    const shellScript = `#!/bin/bash
# Standalone escreg CLI executable
# Fallback script that runs with Bun

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUN_PATH="$(which bun)"

if [ -z "$BUN_PATH" ]; then
    echo "Error: Bun is not installed or not in PATH"
    echo "Please install Bun from https://bun.sh"
    exit 1
fi

exec "$BUN_PATH" "$SCRIPT_DIR/escreg-bundle.js" "$@"
`;

    writeFileSync("dist/executable/escreg.sh", shellScript);
    chmodSync("dist/executable/escreg.sh", 0o755);

    // Create a README for the executable
    const readme = `# Escreg Standalone Executable

This directory contains the standalone executable for the escreg CLI tool.

## Files:

- \`escreg\` - Native executable (requires Bun runtime)
- \`escreg.sh\` - Shell script fallback (requires Bun installed)
- \`escreg-bundle.js\` - Bundled JavaScript (requires Bun runtime)
- \`main.js\` - Entry point script

## Usage:

### Native Executable (Recommended):
\`\`\`bash
./escreg --help
./escreg register 123,456,789
./escreg lookup ADDRESS1,ADDRESS2
./escreg convert 123,456,789
\`\`\`

### Shell Script Fallback:
\`\`\`bash
./escreg.sh --help
\`\`\`

### Direct JavaScript:
\`\`\`bash
bun escreg-bundle.js --help
\`\`\`

## Requirements:

- Linux x64 system
- Bun runtime (for native executable and fallback)
- No Node.js required

## Installation:

1. Copy the \`escreg\` executable to a directory in your PATH
2. Make it executable: \`chmod +x escreg\`
3. Run: \`escreg --help\`

## Build Information:

- Built with Bun
- Target: Linux x64
- Dependencies: Bundled
- Runtime: Bun
`;

    writeFileSync("dist/executable/README.md", readme);

    console.log("✅ Standalone executable created successfully!");
    console.log("📁 Output location: dist/executable/");
    console.log("🚀 Native executable: dist/executable/escreg");
    console.log("📦 Bundled JS: dist/executable/escreg-bundle.js");
    console.log("📝 Shell script: dist/executable/escreg.sh");

    // Test the executable
    console.log("🧪 Testing executable...");
    try {
      const testResult = await $`./dist/executable/escreg --help`;
      console.log("✅ Executable test passed!");
    } catch (error) {
      console.log("⚠️  Native executable test failed, testing shell script...");
      const shellTestResult = await $`./dist/executable/escreg.sh --help`;
      console.log("✅ Shell script test passed!");
    }

  } catch (error) {
    console.error("❌ Build failed:", error);
    process.exit(1);
  }
}

// Run the build
buildExecutable();
